<?php
// this is a pluginless plugin (only a variable def)
$plugin = array(
  'variable' =>  array(
    'varname' => 'css', // choose a unique, descriptive name here, can be the same as plugin label above
    'vardesc' => 'Logical combined sewer system value',
    'vocabulary' => 'epa_echo',
    'varunits' => 'logical',
    'varkey' => 'css',
    'datatype' => 'logical',
    'varcode' => 'CSS',
    'isregular' => 0,
    'timestep' => 0,
    'timeunits' => 'n/a',
    'nodataval' => 0,
    'data_entry' => 'value,code',
    'plugin' => 'dHVariablePluginDefault',
    'options' => '',
    'varabbrev' => 'css',
  ),
);

?>