###############################################################################################################################################
#########################################################State Level Analysis##################################################################

#Primary Author: Morgan McCarthy, M.S. Biological Systems Engineering, Virginia Tech

#-----------------------------------------------------------Purpose---------------------------------------------------------------------------#

# The purpose of this script is to compare withdrawals, discharges, and consumption over time on a state-wide level for the Commonwealth of
# Virginia. Discharge data is withdrawn from the EPA's ECHO system, using the ECHO_Timeseries.R script. This data is then cleaned in the 
# ECHO_QAQC.R script. Withdrawal data is obtained from the VDEQ's VA Hydro system, which is only available through collaboration. Please 
# contact the Office of Water Supply if you are interested in collaboration. Withdrawal data is cleaned in the VWUDS_QAQC.R script. Water
# sectors for each facility in both datasets are classified in the ECHO_QAQC.R and VWUDS_QAQC.R scripts. 

# Consumption, in this analysis, is defined as water that is permanently removed from a water resource system and not replaced. It is 
# calculated as a water balance, with water in being discharges and water out being withdrawals. 

##################################################Library Initilization########################################################################

library(foreign) #allows for easy manipulation of *.dbf file types
library(rgdal) #extract files from file geodatabases-like in ArcMap
library(dplyr)#data manipulation package that speeds up grouping, summarizing, ordering. 
library(XML) #downloads and reads XML file types-used to access ECHORest Services to download facilities
library(RCurl) #downloads and interacts with web-based content
library(readxl) #reads excel files
library(jsonlite)
library(httr)
library(proj4)
library(data.table)
library(stringr)
library(plotly)
library(shiny)
library(lubridate)
library(RColorBrewer)
library(tibble)
library(tidyr)
Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre1.8.0_181')
library(XLConnect)

options(scipen=999) #Disable scientific notation

################################################################Inputs########################################################################

#----------------------------------------------------Cleaned Discharge Data-----------------------------------------------------------------#
# This discharge data was generated by the ECHO_Timeseries.R script and cleaned in the VPDES_QAQC.R Script

#--Load Discharge Timeseries Data--#
ECHO_2010_2017<-read.table("G:/My Drive/ECHO NPDES/USGS_Consumptive_Use_Updated/ECHO_2010_2017_QAQC.txt", sep="\t", header=T)
ECHO_2010_2017<-as.data.table(ECHO_2010_2017)
ECHO_2010_2017<-ECHO_2010_2017[order(ECHO_2010_2017[,1],ECHO_2010_2017[,18],decreasing=F),]
ECHO_2010_2017<-subset(ECHO_2010_2017, subset=ECHO_2010_2017$Permit_Type=="NPDES Individual Permit"&str_sub(ECHO_2010_2017$OutfallID, start=-3)=="001")
ECHO_2010_2017$Resolved_Measured_Effluent_Med<-as.numeric(ECHO_2010_2017$Resolved_Measured_Effluent_Med)

#--696 Unique Facilities--#
ECHO_2010_2017%>%dplyr::group_by(Facility.ID)%>%summarise(Name=first(FacilityName))

ECHO_2010_2017[duplicated(ECHO_2010_2017, by=c("OutfallID","MP_End_Date")),]
ECHO_2010_2017<-ECHO_2010_2017[!duplicated(ECHO_2010_2017, by=c("OutfallID","MP_End_Date")),]

#--Option to Subset into Separate Sectors for Analysis--#
# ECHO_2010_2017<-subset(ECHO_2010_2017, subset=ECHO_2010_2017$Reclass_Use_Type=="Agriculture/Irrigation")
# ECHO_2010_2017<-subset(ECHO_2010_2017, subset=ECHO_2010_2017$Reclass_Use_Type=="Commercial")
# ECHO_2010_2017<-subset(ECHO_2010_2017, subset=ECHO_2010_2017$Reclass_Use_Type=="Energy")
# ECHO_2010_2017<-subset(ECHO_2010_2017, subset=ECHO_2010_2017$Reclass_Use_Type=="Industrial")
# ECHO_2010_2017<-subset(ECHO_2010_2017, subset=ECHO_2010_2017$Reclass_Use_Type=="Municipal")

# ECHO_2010_2017<-subset(ECHO_2010_2017, subset=!ECHO_2010_2017$Reclass_Use_Type=="Energy")

#--Energy Facilities with Matched Withdrawal Facility--#
# ECHO_2010_2017<-subset(ECHO_2010_2017, 
#                        subset=ECHO_2010_2017$Facility.ID=="DC0022004"|
#                          ECHO_2010_2017$Facility.ID=="VA0000370"|
#                          ECHO_2010_2017$Facility.ID=="VA0001015"|
#                          ECHO_2010_2017$Facility.ID=="VA0002071"|
#                          ECHO_2010_2017$Facility.ID=="VA0004090"|
#                          ECHO_2010_2017$Facility.ID=="VA0004138"|
#                          ECHO_2010_2017$Facility.ID=="VA0087645"|
#                          ECHO_2010_2017$Facility.ID=="VA0087033"|
#                          ECHO_2010_2017$Facility.ID=="VA0004146"|
#                          ECHO_2010_2017$Facility.ID=="VA0052451"|
#                          ECHO_2010_2017$Facility.ID=="VA0083402"|
#                          ECHO_2010_2017$Facility.ID=="VA0084069")


#------------------------------------------------------------------------------------------------------------------------------------------#
#-----------------------------------------------Cleaned Withdrawal Data--------------------------------------------------------------------#
# Withdrawal data was obtained through VDEQ's VA Hydro site, which can only be obtained through collaboration.
# Data was analyzed, coordinates were corrected, and water sectors were classified in VWUDS_QAQC.R Script. 

#--Load Withdrawal Timeseries Data--#
load("G:/My Drive/ECHO NPDES/USGS_Consumptive_Use_Updated/Code/R Workspaces/VWUDS_2010_2017.RData")
VWUDS_2010_2017<-as.data.table(VWUDS_2010_2017)
VWUDS_2010_2017<-VWUDS_2010_2017[order(VWUDS_2010_2017[,1],VWUDS_2010_2017[,7],decreasing=F),]

#--1,866 Withdrawing Facilities--#
VWUDS_2010_2017%>%dplyr::group_by(Facility.ID)%>%summarise(Name=first(Facility))

VWUDS_2010_2017[duplicated(VWUDS_2010_2017, by=c("DEQ.ID.of.Source","Date","Million.Gallons.Month")),]
VWUDS_2010_2017<-VWUDS_2010_2017[!duplicated(VWUDS_2010_2017, by=c("DEQ.ID.of.Source","Date","Million.Gallons.Month")),]

#--Option to Subset into Separate Sectors for Analysis--#
# VWUDS_2010_2017<-subset(VWUDS_2010_2017, subset=VWUDS_2010_2017$Reclass_Use_Type=="Agriculture/Irrigation")
# VWUDS_2010_2017<-subset(VWUDS_2010_2017, subset=VWUDS_2010_2017$Reclass_Use_Type=="Commercial")
# VWUDS_2010_2017<-subset(VWUDS_2010_2017, subset=VWUDS_2010_2017$Reclass_Use_Type=="Energy")
# VWUDS_2010_2017<-subset(VWUDS_2010_2017, subset=VWUDS_2010_2017$Reclass_Use_Type=="Industrial")
# VWUDS_2010_2017<-subset(VWUDS_2010_2017, subset=VWUDS_2010_2017$Reclass_Use_Type=="Municipal")
# 
# VWUDS_2010_2017<-subset(VWUDS_2010_2017, subset=!VWUDS_2010_2017$Reclass_Use_Type=="Energy")


#--Energy Facilities with Matched Discharge Facility--#
# VWUDS_2010_2017<-subset(VWUDS_2010_2017,
#                                     subset=VWUDS_2010_2017$Facility.ID=="74082"|
#                                       VWUDS_2010_2017$Facility.ID=="72173"|
#                                       VWUDS_2010_2017$Facility.ID=="72546"|
#                                       VWUDS_2010_2017$Facility.ID=="73170"|
#                                       VWUDS_2010_2017$Facility.ID=="67224"|
#                                       VWUDS_2010_2017$Facility.ID=="73872"|
#                                       VWUDS_2010_2017$Facility.ID=="67174"|
#                                       VWUDS_2010_2017$Facility.ID=="73049"|
#                                       VWUDS_2010_2017$Facility.ID=="73183"|
#                                       VWUDS_2010_2017$Facility.ID=="72023"|
#                                       VWUDS_2010_2017$Facility.ID=="74466"|
#                                       VWUDS_2010_2017$Facility.ID=="73042")

#############################################################Analysis########################################################################

#-------------------------------------------------Statewide Withdrawals vs. Discharges------------------------------------------------------#


#--------------------------------Cumulative Percentage of Total Water Withdrawn by each Facility------------------------------------------#


#--------------------Withdrawals------------------#
# Not all facilities report 12 months out of the year. Therefore, if we want to aggregate monthly withdrawals into yearly estimates for each
# facility, we must divide by the number of reporting months. 

#--Number of Reporting Months for each Source per Year--#
W_Months<-
  VWUDS_2010_2017%>%
  dplyr::group_by(DEQ.ID.of.Source,Year=substring(Date,1,4))%>%
  dplyr::count(Month=substring(Date,6,7))%>%
  dplyr::summarise(Mon_Reported=sum(n))

VWUDS_2010_2017<-
  VWUDS_2010_2017%>%add_column(Year=substring(VWUDS_2010_2017$Date,1,4), .after="Date")

VWUDS_2010_2017<-merge(VWUDS_2010_2017,W_Months,by=c("DEQ.ID.of.Source","Year"),all.x=T)

# save(VWUDS_2010_2017,file="G:/My Drive/ECHO NPDES/USGS_Consumptive_Use_Updated/Code/R Workspaces/VWUDS_2010_2017.RData")


# Withdrawals per year in Millions of Gallons and in MGD
Source_Withdrawals<-VWUDS_2010_2017%>%
  dplyr::group_by(DEQ.ID.of.Source,Year)%>%
  dplyr::summarise(Facility.ID=first(Facility.ID),
                   Facility_Name=first(Facility),
                   Mon_Reported=first(Mon_Reported),
                   Withdrawals_MGal=sum(Million.Gallons.Month,na.rm=T),
                   Withdrawals_MGD=sum(Withdrawals_MGD, na.rm=T)/first(Mon_Reported),
                   Sector=first(Reclass_Use_Type))%>%arrange(desc(Withdrawals_MGD))
                                                                                                

Facility_Withdrawals<-Source_Withdrawals%>%
  dplyr::group_by(Facility.ID,Year)%>%
  dplyr::summarise(Facility_Name=first(Facility_Name),
                   Sources=n_distinct(DEQ.ID.of.Source),
                   Ave_Mon_Reported=mean(Mon_Reported),
                   Withdrawals_MGal=sum(Withdrawals_MGal,na.rm=T),
                   Withdrawals_MGD=sum(Withdrawals_MGD,na.rm=T),
                   Sector=first(Sector))%>%arrange(desc(Withdrawals_MGD))

#--Average Daily Withdrawal in MGD per Year--#
Yearly_Withdrawal<-Source_Withdrawals%>%dplyr::group_by(Year)%>%dplyr::summarise(Withdrawals_MGD=sum(Withdrawals_MGD),nFacilities=n_distinct(Facility.ID))

Monthly_Withdrawal<-
  VWUDS_2010_2017%>%
  dplyr::group_by(Date)%>%
  dplyr::summarise(Withdrawals=sum(Withdrawals_MGD,na.rm=T),
            nFacilities=n_distinct(as.character(Facility.ID)))

#--------------------------------------------#

Withdrawal<-data.frame("Facility.ID"=unique(Facility_Withdrawals$Facility.ID))
Withdrawal$Facility_Name<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID,Facility_Withdrawals$Facility_Name[match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID)],NA)

Withdrawal$MGD_2010<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2010"],Facility_Withdrawals$Withdrawals_MGD[Facility_Withdrawals$Year=="2010"][match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2010"])],NA)
Withdrawal$MGD_2011<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2011"],Facility_Withdrawals$Withdrawals_MGD[Facility_Withdrawals$Year=="2011"][match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2011"])],NA)
Withdrawal$MGD_2012<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2012"],Facility_Withdrawals$Withdrawals_MGD[Facility_Withdrawals$Year=="2012"][match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2012"])],NA)
Withdrawal$MGD_2013<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2013"],Facility_Withdrawals$Withdrawals_MGD[Facility_Withdrawals$Year=="2013"][match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2013"])],NA)
Withdrawal$MGD_2014<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2014"],Facility_Withdrawals$Withdrawals_MGD[Facility_Withdrawals$Year=="2014"][match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2014"])],NA)
Withdrawal$MGD_2015<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2015"],Facility_Withdrawals$Withdrawals_MGD[Facility_Withdrawals$Year=="2015"][match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2015"])],NA)
Withdrawal$MGD_2016<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2016"],Facility_Withdrawals$Withdrawals_MGD[Facility_Withdrawals$Year=="2016"][match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2016"])],NA)
Withdrawal$MGD_2017<-ifelse(Withdrawal$Facility.ID%in%Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2017"],Facility_Withdrawals$Withdrawals_MGD[Facility_Withdrawals$Year=="2017"][match(Withdrawal$Facility.ID,Facility_Withdrawals$Facility.ID[Facility_Withdrawals$Year=="2017"])],NA)

for (i in 1:length(Withdrawal$Facility.ID)){
  Withdrawal$Sum_2010_2017[i]<-(ifelse(is.na(Withdrawal$MGD_2010[i]),0,Withdrawal$MGD_2010[i])+
                                  ifelse(is.na(Withdrawal$MGD_2011[i]),0,Withdrawal$MGD_2011[i])+
                                  ifelse(is.na(Withdrawal$MGD_2012[i]),0,Withdrawal$MGD_2012[i])+
                                  ifelse(is.na(Withdrawal$MGD_2013[i]),0,Withdrawal$MGD_2013[i])+
                                  ifelse(is.na(Withdrawal$MGD_2014[i]),0,Withdrawal$MGD_2014[i])+
                                  ifelse(is.na(Withdrawal$MGD_2015[i]),0,Withdrawal$MGD_2015[i])+
                                  ifelse(is.na(Withdrawal$MGD_2016[i]),0,Withdrawal$MGD_2016[i])+
                                  ifelse(is.na(Withdrawal$MGD_2017[i]),0,Withdrawal$MGD_2017[i]))
}
Withdrawal$Ave_2010_2017<-Withdrawal$Sum_2010_2017/8

# Pecentage of total water withdrawn on average from 2010 to 2017 #
Withdrawal$perc_total<-Withdrawal$Ave_2010_2017/sum(Withdrawal$Ave_2010_2017)
Withdrawal<-Withdrawal%>%arrange(desc(perc_total))

# cumulative percentage
Withdrawal$cum_total<-cumsum(Withdrawal$perc_total)/sum(Withdrawal$perc_total)
n<-count(Withdrawal,Facility.ID)
Withdrawal$cum_fac<-cumsum(n$n)


label1<-list(
  xref='x',
  yref='y',
  x=Withdrawal$cum_fac[1],
  y=Withdrawal$cum_total[1],
  xanchor='left',
  yanchor='middle',
  text= ~paste(round(Withdrawal$cum_total[1],digits=2)),
  font = list(family = 'helvetica', size = 12),
  showarrow = FALSE)

Withdrawal%>%
  plot_ly(x= ~cum_fac)%>%
    add_trace(y = ~cum_total, name="Cumulative Percentage of Total Flow", type = 'scatter', mode = 'lines', line=list(color='red'))%>%
      layout(title = "Cumulative Distribution of % Water Withdrawn: All Sectors",
            xaxis=list(title="# of Facilities"),
            yaxis=list(title="Cumulative % of total Water Withdrawn",
                       range=c(0,1.1)),
            font = list(family= "helvetica", size= 12),
            annotations=label1)


#----------------------Discharges-------------------------#
D_Months<-
  ECHO_2010_2017%>%
  dplyr::group_by(OutfallID,Year=substring(MP_Begin_Date,1,4))%>%
  dplyr::count(Month=substring(MP_End_Date,6,7))%>%
  dplyr::summarise(Mon_Reported=sum(n))

ECHO_2010_2017<-
  ECHO_2010_2017%>%add_column(Year=substring(ECHO_2010_2017$MP_Begin_Date,1,4), .before="MP_Begin_Date")

ECHO_2010_2017<-merge(ECHO_2010_2017,D_Months,by=c("OutfallID","Year"),all.x=T)

# write.table(ECHO_2010_2017,"G:/My Drive/ECHO NPDES/USGS_Consumptive_Use_Updated/ECHO_2010_2017_QAQC.txt", sep="\t", row.names=F)

Outfall_Discharges<-ECHO_2010_2017%>%
  dplyr::group_by(OutfallID,Year)%>%
  dplyr::summarise(Facility.ID=first(Facility.ID),
                   Facility_Name=first(FacilityName),
                   Mon_Reported=first(Mon_Reported),
                   Discharges_MGD=sum(as.numeric(Resolved_Measured_Effluent_Med), na.rm=T)/first(Mon_Reported),
                   Sector=first(Reclass_Use_Type))%>%arrange(desc(Discharges_MGD))

Facility_Discharges<-Outfall_Discharges%>%
  dplyr::group_by(Facility.ID,Year)%>%
  dplyr::summarise(Facility_Name=first(Facility_Name),
                   Outfalls=n_distinct(OutfallID),
                   Ave_Mon_Reported=mean(Mon_Reported),
                   Discharges_MGD=sum(Discharges_MGD, na.rm=T),
                   Sector=first(Sector))%>%arrange(desc(Discharges_MGD))

Facility_Discharges$Facility_Name<-lapply(Facility_Discharges$Facility_Name,as.character)


#--Average Daily Withdrawal in MGD per Year and Month--#
Yearly_Discharge<-Outfall_Discharges%>%dplyr::group_by(Year)%>%dplyr::summarise(Discharges_MGD=sum(Discharges_MGD),nFacilities=n_distinct(Facility.ID))

Monthly_Discharge<-
  ECHO_2010_2017%>%
  group_by(MP_Begin_Date)%>%
  summarise(Discharges=sum(as.numeric(Resolved_Measured_Effluent_Med),na.rm=T),
            nFacilities=n_distinct(as.character(Facility.ID)))

#---------------------------------------------#

Discharge<-data.frame("Facility.ID"=unique(Facility_Discharges$Facility.ID),stringsAsFactors = F)
Discharge$Facility_Name<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID,Facility_Discharges$Facility_Name[match(Discharge$Facility.ID,Facility_Discharges$Facility.ID)],NA)

Discharge$MGD_2010<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2010"],Facility_Discharges$Discharges_MGD[Facility_Discharges$Year=="2010"][match(Discharge$Facility.ID,Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2010"])],NA)
Discharge$MGD_2011<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2011"],Facility_Discharges$Discharges_MGD[Facility_Discharges$Year=="2011"][match(Discharge$Facility.ID,Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2011"])],NA)
Discharge$MGD_2012<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2012"],Facility_Discharges$Discharges_MGD[Facility_Discharges$Year=="2012"][match(Discharge$Facility.ID,Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2012"])],NA)
Discharge$MGD_2013<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2013"],Facility_Discharges$Discharges_MGD[Facility_Discharges$Year=="2013"][match(Discharge$Facility.ID,Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2013"])],NA)
Discharge$MGD_2014<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2014"],Facility_Discharges$Discharges_MGD[Facility_Discharges$Year=="2014"][match(Discharge$Facility.ID,Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2014"])],NA)
Discharge$MGD_2015<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2015"],Facility_Discharges$Discharges_MGD[Facility_Discharges$Year=="2015"][match(Discharge$Facility.ID,Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2015"])],NA)
Discharge$MGD_2016<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2016"],Facility_Discharges$Discharges_MGD[Facility_Discharges$Year=="2016"][match(Discharge$Facility.ID,Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2016"])],NA)
Discharge$MGD_2017<-ifelse(Discharge$Facility.ID%in%Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2017"],Facility_Discharges$Discharges_MGD[Facility_Discharges$Year=="2017"][match(Discharge$Facility.ID,Facility_Discharges$Facility.ID[Facility_Discharges$Year=="2017"])],NA)

for (i in 1:length(Discharge$Facility.ID)){
  Discharge$Sum_2010_2017[i]<-(ifelse(is.na(Discharge$MGD_2010[i]),0,Discharge$MGD_2010[i])+
                                 ifelse(is.na(Discharge$MGD_2011[i]),0,Discharge$MGD_2011[i])+
                                 ifelse(is.na(Discharge$MGD_2012[i]),0,Discharge$MGD_2012[i])+
                                 ifelse(is.na(Discharge$MGD_2013[i]),0,Discharge$MGD_2013[i])+
                                 ifelse(is.na(Discharge$MGD_2014[i]),0,Discharge$MGD_2014[i])+
                                 ifelse(is.na(Discharge$MGD_2015[i]),0,Discharge$MGD_2015[i])+
                                 ifelse(is.na(Discharge$MGD_2016[i]),0,Discharge$MGD_2016[i])+
                                 ifelse(is.na(Discharge$MGD_2017[i]),0,Discharge$MGD_2017[i]))
}
Discharge$Ave_2010_2017<-Discharge$Sum_2010_2017/8

# Pecentage of total water withdrawn on average from 2010 to 2017 #
Discharge$perc_total<-Discharge$Ave_2010_2017/sum(Discharge$Ave_2010_2017)
Discharge<-Discharge%>%arrange(desc(perc_total))

# cumulative percentage
Discharge$cum_total<-cumsum(Discharge$perc_total)/sum(Discharge$perc_total)
n<-count(Discharge,Facility.ID)
Discharge$cum_fac<-cumsum(n$n)


label1<-list(
  xref='x',
  yref='y',
  x=Discharge$cum_fac[1],
  y=Discharge$cum_total[1],
  xanchor='left',
  yanchor='middle',
  text= ~paste(round(Discharge$cum_total[1],digits=2)),
  font = list(family = 'helvetica', size = 12),
  showarrow = FALSE)

Discharge%>%
  plot_ly(x= ~cum_fac)%>%
  add_trace(y = ~cum_total, name="Cumulative Percentage of Total Flow", type = 'scatter', mode = 'lines', line=list(color='blue'))%>%
  layout(title = "Cumulative Distribution of % Water Discharged: All Sectors",
         xaxis=list(title="# of Facilities"),
         yaxis=list(title="Cumulative % of total Water Discharges",
                    range=c(0,1.1)),
         font = list(family= "helvetica", size= 12),
         annotations=label1)

#-------------------------------------------------------Timeseries of Withdrawals vs Discharges-------------------------------------------#

#----------------------------------------------------------Withdrawals--------------------------------------------------------------------#
#-------Mean Daily Withdrawal MGD----------#
label1 <- list(xref = 'x',yref = 'y',
  x = Yearly_Withdrawal$Year[1],
  y = Yearly_Withdrawal$Withdrawals_MGD[1],
  xanchor = 'right',
  yanchor = 'middle',
  text = ~paste(round(Yearly_Withdrawal$Withdrawals_MGD[1],digits=0), 'MGD'),font = list(family = 'Arial', size = 12),showarrow = FALSE)

label2<- list(
  xref = 'x',
  yref = 'y',
  x = Yearly_Withdrawal$Year[8],
  y = Yearly_Withdrawal$Withdrawals_MGD[8],
  xanchor = 'left',
  yanchor = 'bottom',
  text = ~paste(round(Yearly_Withdrawal$Withdrawals_MGD[8],digits=0), 'MGD'),font = list(family = 'Arial', size = 12),showarrow = FALSE)

VWUDS_2010_2017%>%
  group_by(Date)%>%
  summarise(Withdrawals=sum(as.numeric(Withdrawals_MGD), na.rm = T),
            nFacilities=n_distinct(as.character(Facility)))%>%
  plot_ly(x = ~Date)%>%
  add_trace(y = ~Withdrawals, name="Monthly Mean Daily Withdrawal (MGD)",type = 'scatter', mode = 'lines+markers', 
            marker=list(color='red'), line=list(color='red'))%>%
  add_trace(x=Yearly_Withdrawal$Year, y=Yearly_Withdrawal$Withdrawals_MGD, 
            name="Yearly Mean Daily Withdrawal (MGD)",type='scatter',
            mode = 'lines+markers', marker=list(color='black'), line=list(color='black'))%>%
  layout(title = "Statewide Mean Daily Withdrawal in Virginia (MGD)",
         yaxis = list(title="Mean Daily Withdrawal (MGD)",
                      tickfont=list(color="black"),
                      range=c(0,10500)), #10500 all sectors 
         xaxis = list(title = "Date"),
         margin=list(r=125),
         legend=list(x=0.75, y=0.1),
         annotations=label1)%>%
  layout(annotations=label2)

#----------------------------------------------------------Discharges--------------------------------------------------------------------#
#-------Mean Daily Discharge MGD----------#

label1 <- list(
  xref = 'x',
  yref = 'y',
  x = Yearly_Discharge$Year[1],
  y = Yearly_Discharge$Discharges_MGD[1],
  xanchor = 'right',
  yanchor = 'middle',
  text = ~paste(round(Yearly_Discharge$Discharges_MGD[1],digits=0), 'MGD'),
  font = list(family = 'Arial',size = 12),showarrow = FALSE)

label2 <- list(
  xref = 'x',
  yref = 'y',
  x = Yearly_Discharge$Year[8],
  y = Yearly_Discharge$Discharges_MGD[8],
  xanchor = 'left',
  yanchor = 'bottom',
  text = ~paste(round(Yearly_Discharge$Discharges_MGD[8],digits=0), 'MGD'),
  font = list(family = 'Arial',size = 12,color = 'rgba(67,67,67,1)'),showarrow = FALSE)

ECHO_2010_2017$MP_Begin_Date<-as.Date(ECHO_2010_2017$MP_Begin_Date,format="%Y-%m-%d")

ECHO_2010_2017%>%
  group_by(MP_Begin_Date)%>%
  summarise(Discharges=sum(Resolved_Measured_Effluent_Med,na.rm=T),
            nFacilities=n_distinct(as.character(Facility.ID)))%>%
  plot_ly(x = ~MP_Begin_Date)%>%
  add_trace(y = ~Discharges, name="Monthly Mean Daily Discharge (MGD)", type='scatter', mode = 'lines+markers', marker=list(color='blue'), line=list(color='blue'))%>%
  add_trace(x=Yearly_Discharge$Year, y=Yearly_Discharge$Discharges_MGD, name="Yearly Mean Daily Discharge (MGD)",type='scatter',
            mode = 'lines+markers', marker=list(color='black'), line=list(color='black'))%>%
  layout(title = "Statewide Mean Daily Discharge (MGD) in Virginia",
         yaxis = list(title="Mean Daily Withdrawal (MGD)",
                      tickfont=list(color="blue"),
                      range=c(0,8500)),
         xaxis = list(title = "Date"),
         margin=list(r=125),
         legend=list(x=0.75, y=0.1),
         annotations=label1)%>%
  layout(annotations=label2)

#-----Monthly Withdrawals vs Discharges with Consumption lines-------#

CU<-data.frame(Date=Monthly_Discharge$MP_Begin_Date,
               CU=(Monthly_Withdrawal$Withdrawals-Monthly_Discharge$Discharges)/
                 Monthly_Withdrawal$Withdrawals)

VWUDS_2010_2017%>%
  group_by(Date)%>%
  summarise(Withdrawals=sum(as.numeric(Withdrawals_MGD), na.rm = T),
            nFacilities=n_distinct(as.character(Facility)))%>%
  plot_ly(x = ~Date)%>%
  add_trace(y = ~Withdrawals, name="Monthly Mean Daily Withdrawals (MGD)",type = 'scatter', mode = 'lines+markers', marker=list(color='red'), line=list(color='red'))%>%
  add_trace(x=Monthly_Discharge$MP_Begin_Date, y=Monthly_Discharge$Discharges, name="Monthly Mean Daily Discharges (MGD)", type="scatter", mode='lines+markers',marker=list(color='blue'), line=list(color='blue'))%>%
  add_trace(x=CU$Date, y=CU$CU, name="Consumptive Coefficient", type="scatter", yaxis="y2", mode='lines+markers', marker=list(color='#969696'),line=list(color='#969696'))%>%
  layout(title = "Statewide Mean Daily Withdrawals vs. Discharges (MGD) in Virginia",
         yaxis = list(title="Mean Daily Quantity (MGD)",
                      range=c(0,10500)),
         yaxis2=list(tickfont=list(color="black"),
                     overlaying="y",
                     side="right",
                     title="Consumptive Coefficient",
                     range=c(-0.2,1)),
         margin=list(r=125),
         xaxis = list(title = "Monitoring Period (Months)"),
         legend=list(x=0.8, y=-0.2))


#------Compare number of facilities------#

VWUDS_2010_2017%>%
  group_by(Date=substr(Date,1,4))%>%
  summarise(Withdrawals=sum(as.numeric(Withdrawals_MGD), na.rm = T)/12,
            nFacilities=n_distinct(as.character(Facility)))%>%
  plot_ly(x = ~Date)%>%
  add_trace(y=~nFacilities, name="Withdrawing Facilities", type="bar", marker=list(color="red"))%>%
  add_trace(x=Yearly_Discharge$Year,y=Yearly_Discharge$nFacilities, name="Discharging Facilities", type="bar",marker=list(color="blue") )%>%
  layout(title="Number of Reporting Facilities per Year",
         yaxis=list(title="Number of Facilities"))




#----------------------------------------------------------------------------------------------------------------------------------------------#
#------------------------------------------Consumption Coefficients per Sector per Year--------------------------------------------------------#

Sector_Discharge<-Facility_Discharges%>%
  dplyr::group_by(Sector,Year)%>%
  dplyr::summarise(nFacilities=n_distinct(Facility.ID),
                   Discharges_MGD=sum(Discharges_MGD,na.rm=T))



Sector_Withdrawal<-Facility_Withdrawals%>%
  dplyr::group_by(Sector,Year)%>%
  dplyr::summarise(nFacilities=n_distinct(Facility.ID),
                   Withdrawals_MGD=sum(Withdrawals_MGD,na.rm=T))

Sector_CU<-data.frame("Sector"=unique(Sector_Withdrawal$Sector),stringsAsFactors = F)

Sector_CU$Discharge_MGD2010<-ifelse(Sector_CU$Sector%in%Sector_Discharge$Sector[Sector_Discharge$Year=="2010"],Sector_Discharge$Discharges_MGD[Sector_Discharge$Year=="2010"][match(Sector_CU$Sector,Sector_Discharge$Sector[Sector_Discharge$Year=="2010"])],NA)
Sector_CU$Discharge_MGD2011<-ifelse(Sector_CU$Sector%in%Sector_Discharge$Sector[Sector_Discharge$Year=="2011"],Sector_Discharge$Discharges_MGD[Sector_Discharge$Year=="2011"][match(Sector_CU$Sector,Sector_Discharge$Sector[Sector_Discharge$Year=="2011"])],NA)
Sector_CU$Discharge_MGD2012<-ifelse(Sector_CU$Sector%in%Sector_Discharge$Sector[Sector_Discharge$Year=="2012"],Sector_Discharge$Discharges_MGD[Sector_Discharge$Year=="2012"][match(Sector_CU$Sector,Sector_Discharge$Sector[Sector_Discharge$Year=="2012"])],NA)
Sector_CU$Discharge_MGD2013<-ifelse(Sector_CU$Sector%in%Sector_Discharge$Sector[Sector_Discharge$Year=="2013"],Sector_Discharge$Discharges_MGD[Sector_Discharge$Year=="2013"][match(Sector_CU$Sector,Sector_Discharge$Sector[Sector_Discharge$Year=="2013"])],NA)
Sector_CU$Discharge_MGD2014<-ifelse(Sector_CU$Sector%in%Sector_Discharge$Sector[Sector_Discharge$Year=="2014"],Sector_Discharge$Discharges_MGD[Sector_Discharge$Year=="2014"][match(Sector_CU$Sector,Sector_Discharge$Sector[Sector_Discharge$Year=="2014"])],NA)
Sector_CU$Discharge_MGD2015<-ifelse(Sector_CU$Sector%in%Sector_Discharge$Sector[Sector_Discharge$Year=="2015"],Sector_Discharge$Discharges_MGD[Sector_Discharge$Year=="2015"][match(Sector_CU$Sector,Sector_Discharge$Sector[Sector_Discharge$Year=="2015"])],NA)
Sector_CU$Discharge_MGD2016<-ifelse(Sector_CU$Sector%in%Sector_Discharge$Sector[Sector_Discharge$Year=="2016"],Sector_Discharge$Discharges_MGD[Sector_Discharge$Year=="2016"][match(Sector_CU$Sector,Sector_Discharge$Sector[Sector_Discharge$Year=="2016"])],NA)
Sector_CU$Discharge_MGD2017<-ifelse(Sector_CU$Sector%in%Sector_Discharge$Sector[Sector_Discharge$Year=="2017"],Sector_Discharge$Discharges_MGD[Sector_Discharge$Year=="2017"][match(Sector_CU$Sector,Sector_Discharge$Sector[Sector_Discharge$Year=="2017"])],NA)

Sector_CU$Withdrawal_MGD2010<-ifelse(Sector_CU$Sector%in%Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2010"],Sector_Withdrawal$Withdrawals_MGD[Sector_Withdrawal$Year=="2010"][match(Sector_CU$Sector,Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2010"])],NA)
Sector_CU$Withdrawal_MGD2011<-ifelse(Sector_CU$Sector%in%Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2011"],Sector_Withdrawal$Withdrawals_MGD[Sector_Withdrawal$Year=="2011"][match(Sector_CU$Sector,Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2011"])],NA)
Sector_CU$Withdrawal_MGD2012<-ifelse(Sector_CU$Sector%in%Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2012"],Sector_Withdrawal$Withdrawals_MGD[Sector_Withdrawal$Year=="2012"][match(Sector_CU$Sector,Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2012"])],NA)
Sector_CU$Withdrawal_MGD2013<-ifelse(Sector_CU$Sector%in%Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2013"],Sector_Withdrawal$Withdrawals_MGD[Sector_Withdrawal$Year=="2013"][match(Sector_CU$Sector,Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2013"])],NA)
Sector_CU$Withdrawal_MGD2014<-ifelse(Sector_CU$Sector%in%Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2014"],Sector_Withdrawal$Withdrawals_MGD[Sector_Withdrawal$Year=="2014"][match(Sector_CU$Sector,Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2014"])],NA)
Sector_CU$Withdrawal_MGD2015<-ifelse(Sector_CU$Sector%in%Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2015"],Sector_Withdrawal$Withdrawals_MGD[Sector_Withdrawal$Year=="2015"][match(Sector_CU$Sector,Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2015"])],NA)
Sector_CU$Withdrawal_MGD2016<-ifelse(Sector_CU$Sector%in%Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2016"],Sector_Withdrawal$Withdrawals_MGD[Sector_Withdrawal$Year=="2016"][match(Sector_CU$Sector,Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2016"])],NA)
Sector_CU$Withdrawal_MGD2017<-ifelse(Sector_CU$Sector%in%Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2017"],Sector_Withdrawal$Withdrawals_MGD[Sector_Withdrawal$Year=="2017"][match(Sector_CU$Sector,Sector_Withdrawal$Sector[Sector_Withdrawal$Year=="2017"])],NA)

Sector_CU$CU_2010<-(ifelse(is.na(Sector_CU$Withdrawal_MGD2010),0,Sector_CU$Withdrawal_MGD2010)-
                    ifelse(is.na(Sector_CU$Discharge_MGD2010),0,Sector_CU$Discharge_MGD2010))/(ifelse(is.na(Sector_CU$Withdrawal_MGD2010),0,Sector_CU$Withdrawal_MGD2010))

Sector_CU$CU_2011<-(ifelse(is.na(Sector_CU$Withdrawal_MGD2011),0,Sector_CU$Withdrawal_MGD2011)-
                      ifelse(is.na(Sector_CU$Discharge_MGD2011),0,Sector_CU$Discharge_MGD2011))/(ifelse(is.na(Sector_CU$Withdrawal_MGD2011),0,Sector_CU$Withdrawal_MGD2011))


Sector_CU$CU_2012<-(ifelse(is.na(Sector_CU$Withdrawal_MGD2012),0,Sector_CU$Withdrawal_MGD2012)-
                      ifelse(is.na(Sector_CU$Discharge_MGD2012),0,Sector_CU$Discharge_MGD2012))/(ifelse(is.na(Sector_CU$Withdrawal_MGD2012),0,Sector_CU$Withdrawal_MGD2012))

Sector_CU$CU_2013<-(ifelse(is.na(Sector_CU$Withdrawal_MGD2013),0,Sector_CU$Withdrawal_MGD2013)-
                      ifelse(is.na(Sector_CU$Discharge_MGD2013),0,Sector_CU$Discharge_MGD2013))/(ifelse(is.na(Sector_CU$Withdrawal_MGD2013),0,Sector_CU$Withdrawal_MGD2013))

Sector_CU$CU_2014<-(ifelse(is.na(Sector_CU$Withdrawal_MGD2014),0,Sector_CU$Withdrawal_MGD2014)-
                      ifelse(is.na(Sector_CU$Discharge_MGD2014),0,Sector_CU$Discharge_MGD2014))/(ifelse(is.na(Sector_CU$Withdrawal_MGD2014),0,Sector_CU$Withdrawal_MGD2014))

Sector_CU$CU_2015<-(ifelse(is.na(Sector_CU$Withdrawal_MGD2015),0,Sector_CU$Withdrawal_MGD2015)-
                      ifelse(is.na(Sector_CU$Discharge_MGD2015),0,Sector_CU$Discharge_MGD2015))/(ifelse(is.na(Sector_CU$Withdrawal_MGD2015),0,Sector_CU$Withdrawal_MGD2015))

Sector_CU$CU_2016<-(ifelse(is.na(Sector_CU$Withdrawal_MGD2016),0,Sector_CU$Withdrawal_MGD2016)-
                      ifelse(is.na(Sector_CU$Discharge_MGD2016),0,Sector_CU$Discharge_MGD2016))/(ifelse(is.na(Sector_CU$Withdrawal_MGD2016),0,Sector_CU$Withdrawal_MGD2016))

Sector_CU$CU_2017<-(ifelse(is.na(Sector_CU$Withdrawal_MGD2017),0,Sector_CU$Withdrawal_MGD2017)-
                      ifelse(is.na(Sector_CU$Discharge_MGD2017),0,Sector_CU$Discharge_MGD2017))/(ifelse(is.na(Sector_CU$Withdrawal_MGD2017),0,Sector_CU$Withdrawal_MGD2017))
Sector_CU<-Sector_CU[-c(2:17)]

for (i in 1:length(Sector_CU$Sector)){
  Sector_CU$Sum[i]<-(Sector_CU$CU_2010[i]+
                    Sector_CU$CU_2011[i]+
                    Sector_CU$CU_2012[i]+
                    Sector_CU$CU_2013[i]+
                    Sector_CU$CU_2014[i]+
                    Sector_CU$CU_2015[i]+
                    Sector_CU$CU_2016[i]+
                    Sector_CU$CU_2017[i])
}
Sector_CU$Ave<-Sector_CU$Sum/8

#----------------------------------------------------------------------------------------------------------------------------------------------#

Municipal.Usage.by.Category.Year<-
VWUDS_2010_2017[VWUDS_2010_2017$Reclass_Use_Type=="Municipal"]%>%
  group_by(Year=(substr(Date,1,4)),Use.Type= Reclass_Use_Type)%>%
  summarise(Sum=sum(Withdrawals_MGD,na.rm = T),
            Average=mean(Withdrawals_MGD,na.rm=T),
            Median=median(Withdrawals_MGD,na.rm=T),
            Minimum=min(Withdrawals_MGD,na.rm=T),
            Maximum=max(Withdrawals_MGD,na.rm=T),
            no_submissions=n())

Resolved_Discharge.by.Category.Year<-
  ECHO_2010_2017%>%
  group_by(Year=(substr(MP_Begin_Date,1,4)),Use_Type=Reclass_Use_Type)%>%
  summarise(Sum=sum(Resolved_Measured_Effluent_NA,na.rm = T),
            Average=mean(Resolved_Measured_Effluent_NA,na.rm=T),
            Median=median(Resolved_Measured_Effluent_NA,na.rm=T),
            Minimum=min(Resolved_Measured_Effluent_NA,na.rm=T),
            Maximum=max(Resolved_Measured_Effluent_NA,na.rm=T),
            no_submissions=n())

#---------Median Compare------------------#
colors_usage <- brewer.pal(9, "YlOrRd")
colors_discharge <- brewer.pal(9, "PuBu")

Median_Withdrawal<-
  plot_ly(Usage.by.Category.Year, y = ~Use.Type[1:3], x = ~Median[1:3], type='bar', name="2010", orientation='h',
        text=c("2010","2010","2010"),
        marker= list(color=colors_usage[9]))%>%
  add_trace(x = ~Median[4:6], name= "2011", 
            text=c("2011","2011","2011"),
            marker= list(color=colors_usage[8]))%>%
  add_trace(x = ~Median[7:9], name= "2012", 
            text=c("2012","2012","2012"),
            marker= list(color=colors_usage[7]))%>%
  add_trace(x = ~Median[10:12], name= "2013",
            text=c("2013","2013","2013"),
            marker= list(color=colors_usage[6]))%>%
  add_trace(x = ~Median[13:15], name= "2014",
            text=c("2014","2014","2014"),
            marker= list(color=colors_usage[5]))%>%
  add_trace(x = ~Median[16:18], name= "2015",
            text=c("2015","2015","2015"),
            marker= list(color=colors_usage[4]))%>%
  add_trace(x = ~Median[19:21], name= "2016",
            text=c("2016","2016","2016"),
            marker= list(color=colors_usage[3]))%>%
  add_trace(x = ~Median[22:24], name= "2017",
            text=c("2017","2017","2017"),
            marker= list(color=colors_usage[2]))%>%
  layout(title="Median Withdrawal (MGD) Per Water Sector Per Year",
         xaxis = list(title='Median Withdrawal (MGD)'), 
         yaxis= list(title='Water Use Sector'),
         barmode='stack')

Median_Discharge<-
  plot_ly(Resolved_Discharge.by.Category.Year, y = ~Use_Type[1:2], x = ~Median[1:2], type='bar', name="2010", orientation='h',
          text=c("2010","2010"),
          marker= list(color=colors_discharge[9]))%>%
  add_trace(x = ~Median[3:4], name= "2011", 
            text=c("2011","2011"),
            marker= list(color=colors_discharge[8]))%>%
  add_trace(x = ~Median[5:6], name= "2012", 
            text=c("2012","2012"),
            marker= list(color=colors_discharge[7]))%>%
  add_trace(x = ~Median[7:8], name= "2013",
            text=c("2013","2013"),
            marker= list(color=colors_discharge[6]))%>%
  add_trace(x = ~Median[9:10], name= "2014",
            text=c("2014","2014"),
            marker= list(color=colors_discharge[5]))%>%
  add_trace(x = ~Median[11:12], name= "2015",
            text=c("2015","2015"),
            marker= list(color=colors_discharge[4]))%>%
  add_trace(x = ~Median[13:14], name= "2016",
            text=c("2016","2016"),
            marker= list(color=colors_discharge[3]))%>%
  add_trace(x = ~Median[15:16], name= "2017",
            text=c("2017","2017"),
            marker= list(color=colors_discharge[2]))%>%
  layout(xaxis = list(title='Median Quantity (MGD)'), 
         yaxis = list(title='Water Sector'),
         title = "Median Discharge per Water Sector per Year",
         barmode='stack')


subplot(Median_Withdrawal,Median_Discharge, nrows=2, shareX = T, titleX=T)%>%
  layout(title="Median Withdrawals vs. Discharges (MGD) per Sector")

#--------------Mean Compare-------------------#
Mean_Withdrawal<-
  plot_ly(Usage.by.Category.Year, y = ~Use.Type[1:3], x = ~Average[1:3], type='bar', name="2010", orientation='h',
          text=c("2010","2010","2010"),
          marker= list(color=colors_usage[9]))%>%
  add_trace(x = ~Average[4:6], name= "2011", 
            text=c("2011","2011","2011"),
            marker= list(color=colors_usage[8]))%>%
  add_trace(x = ~Average[7:9], name= "2012", 
            text=c("2012","2012","2012"),
            marker= list(color=colors_usage[7]))%>%
  add_trace(x = ~Average[10:12], name= "2013",
            text=c("2013","2013","2013"),
            marker= list(color=colors_usage[6]))%>%
  add_trace(x = ~Average[13:15], name= "2014",
            text=c("2014","2014","2014"),
            marker= list(color=colors_usage[5]))%>%
  add_trace(x = ~Average[16:18], name= "2015",
            text=c("2015","2015","2015"),
            marker= list(color=colors_usage[4]))%>%
  add_trace(x = ~Average[19:21], name= "2016",
            text=c("2016","2016","2016"),
            marker= list(color=colors_usage[3]))%>%
  add_trace(x = ~Average[22:24], name= "2017",
            text=c("2017","2017","2017"),
            marker= list(color=colors_usage[2]))%>%
  layout(title="Mean Withdrawal (MGD) Per Water Sector Per Year",
         xaxis = list(title='Mean Withdrawal (MGD)'), 
         yaxis= list(title='Water Use Sector'),
         barmode='stack')

Mean_Discharge<-
  plot_ly(Resolved_Discharge.by.Category.Year, y = ~Use_Type[1:2], x = ~Average[1:2], type='bar', name="2010", orientation='h',
          text=c("2010","2010"),
          marker= list(color=colors_discharge[9]))%>%
  add_trace(x = ~Average[3:4], name= "2011", 
            text=c("2011","2011"),
            marker= list(color=colors_discharge[8]))%>%
  add_trace(x = ~Average[5:6], name= "2012", 
            text=c("2012","2012"),
            marker= list(color=colors_discharge[7]))%>%
  add_trace(x = ~Average[7:8], name= "2013",
            text=c("2013","2013"),
            marker= list(color=colors_discharge[6]))%>%
  add_trace(x = ~Average[9:10], name= "2014",
            text=c("2014","2014"),
            marker= list(color=colors_discharge[5]))%>%
  add_trace(x = ~Average[11:12], name= "2015",
            text=c("2015","2015"),
            marker= list(color=colors_discharge[4]))%>%
  add_trace(x = ~Average[13:14], name= "2016",
            text=c("2016","2016"),
            marker= list(color=colors_discharge[3]))%>%
  add_trace(x = ~Average[15:16], name= "2017",
            text=c("2017","2017"),
            marker= list(color=colors_discharge[2]))%>%
  layout(xaxis = list(title='Mean Quantity (MGD)'), 
         yaxis = list(title='Water Sector'),
         title = "Mean Discharge (MGD) per Water Sector per Year",
         barmode='stack')

subplot(Mean_Withdrawal,Mean_Discharge, nrows=2, shareX = T, titleX=T)%>%
  layout(title="Mean Withdrawals vs. Discharges (MGD) per Sector")




#----------Submissions over Time-----------------#

VWUDS_Submissions<-
  plot_ly(Usage.by.Category.Year, y = ~Use.Type[1:3], x = ~no_submissions[1:3], type='bar', name="2010", orientation='h',
          text=c("2010","2010","2010"),
          marker= list(color=colors_usage[9]))%>%
  add_trace(x = ~no_submissions[4:6], name= "2011", 
            text=c("2011","2011","2011"),
            marker= list(color=colors_usage[8]))%>%
  add_trace(x = ~no_submissions[7:9], name= "2012", 
            text=c("2012","2012","2012"),
            marker= list(color=colors_usage[7]))%>%
  add_trace(x = ~no_submissions[10:12], name= "2013",
            text=c("2013","2013","2013"),
            marker= list(color=colors_usage[6]))%>%
  add_trace(x = ~no_submissions[13:15], name= "2014",
            text=c("2014","2014","2014"),
            marker= list(color=colors_usage[5]))%>%
  add_trace(x = ~no_submissions[16:18], name= "2015",
            text=c("2015","2015","2015"),
            marker= list(color=colors_usage[4]))%>%
  add_trace(x = ~no_submissions[19:21], name= "2016",
            text=c("2016","2016","2016"),
            marker= list(color=colors_usage[3]))%>%
  add_trace(x = ~no_submissions[22:24], name= "2017",
            text=c("2017","2017","2017"),
            marker= list(color=colors_usage[2]))%>%
  layout(title="Submissions Per Water Sector Per Year",
         xaxis = list(title='Number of Submissions'), 
         yaxis= list(title='Water Use Sector'),
         barmode='stack')

ECHO_Submissions<-
  plot_ly(Resolved_Discharge.by.Category.Year, y = ~Use_Type[1:2], x = ~no_submissions[1:2], type='bar', name="2010", orientation='h',
          text=c("2010","2010"),
          marker= list(color=colors_discharge[9]))%>%
  add_trace(x = ~no_submissions[3:4], name= "2011", 
            text=c("2011","2011"),
            marker= list(color=colors_discharge[8]))%>%
  add_trace(x = ~no_submissions[5:6], name= "2012", 
            text=c("2012","2012"),
            marker= list(color=colors_discharge[7]))%>%
  add_trace(x = ~no_submissions[7:8], name= "2013",
            text=c("2013","2013"),
            marker= list(color=colors_discharge[6]))%>%
  add_trace(x = ~no_submissions[9:10], name= "2014",
            text=c("2014","2014"),
            marker= list(color=colors_discharge[5]))%>%
  add_trace(x = ~no_submissions[11:12], name= "2015",
            text=c("2015","2015"),
            marker= list(color=colors_discharge[4]))%>%
  add_trace(x = ~no_submissions[13:14], name= "2016",
            text=c("2016","2016"),
            marker= list(color=colors_discharge[3]))%>%
  add_trace(x = ~no_submissions[15:16], name= "2017",
            text=c("2017","2017"),
            marker= list(color=colors_discharge[2]))%>%
  layout(xaxis = list(title='Number of Submissions'), 
         yaxis = list(title='Water Sector'),
         title = "Number of Submissions per Water Sector per Year",
         barmode='stack')

subplot(VWUDS_Submissions,ECHO_Submissions, nrows=2, shareX=T, titleX=T)%>%
  layout(title="Number of Withdrawal/Discharge Submissions Per Sector Per Year")
